#!/bin/bash

#Murillo 11/7/2023

# Prompt the user for a guess
echo "OK Human, guess the number I am thinking of."
echo "It's a whole number between 1 and 10."

# Read the user's guess
read -p "Your guess: " ANSWER01

# Define the secret number
SECRET_NUMBER=7

# Check if the guess is correct
if [ "$ANSWER01" -eq $SECRET_NUMBER ]; then
    echo "You are correct, human. Congratulations!"
else
    echo "Your guess is incorrect. Try again."
fi

cat $0 > answer61.txt
